import { z } from 'zod';
import { isoDateSchema } from './date.js';

/**
 * Milestone 1 open-case contract. Deliberately excludes identity-sensitive
 * credentials (passport numbers, bank details) — those arrive with the
 * encrypted-field/document design, never as plain request fields
 * (database-blueprint.md §4.2, Constitution §16).
 */
export const openEmploymentCaseRequestSchema = z.object({
  careRecipient: z.object({
    fullName: z.string().trim().min(2).max(120),
    careLevel: z.string().trim().max(60).optional(),
    city: z.string().trim().max(80).optional(),
  }),
  employer: z.object({
    fullName: z.string().trim().min(2).max(120),
    relationshipToRecipient: z.string().trim().min(2).max(60),
    city: z.string().trim().max(80).optional(),
  }),
  caregiver: z.object({
    legalName: z.string().trim().min(2).max(120),
    preferredName: z.string().trim().max(120).optional(),
    nationality: z.string().trim().min(2).max(60),
    primaryLanguage: z.string().trim().max(60).optional(),
  }),
  startDate: isoDateSchema,
  /**
   * Optional provenance link to the legacy browser client this case is being
   * opened for (ADR-006). Supplying it makes the request idempotent: opening a
   * case twice for the same local client returns the first case instead of
   * creating a second, which is what makes it safe to call at the end of
   * onboarding and to retry afterwards.
   *
   * It is an opaque identifier generated by the browser and carries no personal
   * data, so it is not a sensitive identifier under ADR-006 clause 7.
   */
  legacyClientId: z.string().trim().min(1).max(200).optional(),
});

export type OpenEmploymentCaseRequest = z.infer<typeof openEmploymentCaseRequestSchema>;

export const employmentCaseResponseSchema = z.object({
  id: z.string(),
  status: z.string(),
  startDate: z.string(),
  endDate: z.string().nullable(),
  /**
   * Null for every case that existed before migration 0042 and for every case
   * opened directly in the canonical product. The web client uses it to answer
   * "which canonical case is this local client?" from the canonical side, so
   * that the browser snapshot never holds the migration's own bookkeeping.
   */
  legacyClientId: z.string().nullable(),
  careRecipient: z.object({
    id: z.string(),
    fullName: z.string(),
    careLevel: z.string().nullable(),
    city: z.string().nullable(),
  }),
  employer: z.object({
    id: z.string(),
    fullName: z.string(),
    relationshipToRecipient: z.string(),
    city: z.string().nullable(),
  }),
  caregiver: z.object({
    id: z.string(),
    legalName: z.string(),
    preferredName: z.string().nullable(),
    nationality: z.string(),
    primaryLanguage: z.string().nullable(),
  }),
});

export type EmploymentCaseResponse = z.infer<typeof employmentCaseResponseSchema>;
