import type { Task, TimelineEvent } from '@caredesk/domain';

/**
 * What the repository needs to persist a task — ids and resolved values,
 * distinct from the use case's `CreateTaskInput`, which is the caller-facing
 * shape (a due *date*, no ids, optional fields).
 */
export interface CreateTaskRecord {
  id: string;
  tenantId: string;
  employmentCaseId: string;
  /**
   * Exactly one of `title`/`titleKey` is set, matching the database's
   * `task_has_exactly_one_title` check. User-typed tasks (CreateCaseTask,
   * ImportCaseTask) set `title`; system-seeded tasks (case-open compliance
   * seeding) set `titleKey` so the label renders translated instead of a
   * frozen English/Hebrew string baked into a database row.
   */
  title?: string;
  titleKey?: string;
  description: string | null;
  priority: Task['priority'];
  dueAt: string | null;
  createdBy: string;
  /** Set only by ImportCaseTask — see Task.legacyLocalId. */
  legacyLocalId?: string | null;
  /**
   * Set only by system-seeded tasks — see Task.sourceKey. Distinct from
   * legacyLocalId: this key is generated by the server itself, never by a
   * browser-only record.
   */
  sourceKey?: string | null;
  /** Defaults to 'manual' at the database layer; seeding passes 'rule'. */
  sourceType?: Task['sourceType'];
}

/** Only the fields a caller may edit; status transitions go through completeTask/archiveTask. */
export interface UpdateTaskRecord {
  title?: string;
  description?: string | null;
  priority?: Task['priority'];
  dueAt?: string | null;
}

export interface TaskRepository {
  createTask(input: CreateTaskRecord): Promise<Task>;
  listTasks(tenantId: string, employmentCaseId: string): Promise<Task[]>;
  findTask(tenantId: string, taskId: string): Promise<Task | null>;
  /**
   * The task previously imported from this local id, or null. Read before any
   * import write so a repeated import returns the existing row instead of the
   * application layer racing the database's own unique index.
   */
  findTaskByLegacyLocalId(
    tenantId: string,
    employmentCaseId: string,
    legacyLocalId: string,
  ): Promise<Task | null>;
  /**
   * The task previously seeded under this source key, or null. Read before
   * any system-seeding write — same "find first" idempotence shape as
   * findTaskByLegacyLocalId, but for server-generated rows (see Task.sourceKey).
   */
  findTaskBySourceKey(
    tenantId: string,
    employmentCaseId: string,
    sourceKey: string,
  ): Promise<Task | null>;
  /** Returns null when the task does not exist or is already completed. */
  completeTask(
    tenantId: string,
    taskId: string,
    completedAt: string,
    completedBy: string,
  ): Promise<Task | null>;
  /**
   * Completes the open task seeded under this source key (see Task.sourceKey),
   * or does nothing and returns null when no such task exists or it is already
   * completed. This is the self-resolution half of the seeding in
   * OpenEmploymentCase: a document becoming currently valid closes the task
   * that was asking for it, the same way completeTask does for a human click,
   * but addressed by the deterministic key instead of a task id the caller
   * would otherwise have to look up first (and race).
   *
   * `completedBy` is null for an automatic completion — no human clicked
   * anything, so nothing should be attributed to a user id (mirrors
   * AuditEventInput.actorId's null-for-system-actor convention). Passing a
   * real user id is intentionally still allowed for symmetry with
   * completeTask, in case a future caller ever needs it.
   */
  completeTaskBySourceKey(
    tenantId: string,
    employmentCaseId: string,
    sourceKey: string,
    completedAt: string,
    completedBy: string | null,
  ): Promise<Task | null>;
  /** Returns null when the task does not exist or is already completed/cancelled. */
  updateTask(
    tenantId: string,
    taskId: string,
    changes: UpdateTaskRecord,
    updatedBy: string,
  ): Promise<Task | null>;
  /**
   * Soft-close: sets status to 'cancelled'. There is no delete verb — an
   * archived task must remain reconstructable in the same way a document or a
   * timeline entry does. Returns null when the task does not exist or is
   * already completed/cancelled.
   */
  archiveTask(tenantId: string, taskId: string, updatedBy: string): Promise<Task | null>;
}

export interface TimelineRepository {
  listTimeline(tenantId: string, employmentCaseId: string): Promise<TimelineEvent[]>;
}
