-- ADR-006 clause 1/3: the normalized aggregate is canonical and the browser
-- snapshot (`caredesk.mvp.*` in localStorage, `tenant_workspace.payload`) is a
-- transitional compatibility mechanism. Code review WEB-11 found the reason the
-- migration had stalled: nothing in the product creates an `employment_case`,
-- so the canonical module was unreachable and every canonical screen was a dead
-- end. Reaching case creation from the real journey needs one thing the schema
-- did not have - a way to say "this canonical case IS the client the user set
-- up in onboarding".
--
-- WHY THE LINK LIVES HERE AND NOT IN THE BROWSER
-- ----------------------------------------------
-- The obvious place to record it is next to the client, in the snapshot. That
-- is exactly the mistake the ADR forbids (clause 5) and exactly the mistake
-- that made this root: the map from legacy to canonical would then live only in
-- the store we are migrating away from, unprotected by
-- `tenant_workspace_history`, `tenant_data_census`, RLS, or backups, and lost
-- with a cleared browser. Storing it on the canonical row instead means the
-- canonical table can always answer "which local client am I?" on its own, and
-- the snapshot never becomes load-bearing for the migration itself.
--
-- WRITE AUTHORITY (ADR-006 clause 6)
-- ----------------------------------
-- `legacy_client_id` is written exactly once, by `OpenEmploymentCase`, at
-- creation. Nothing updates it. It is an opaque provenance marker - the local
-- client identifier is a random uuid generated by the browser and carries no
-- personal data - so it is not a sensitive identifier under clause 7.
--
-- IDEMPOTENCE
-- -----------
-- Onboarding can be completed more than once (re-run, retry after a failed
-- request, two tabs). The partial unique index makes a duplicate case for the
-- same local client impossible at the database layer; the application checks
-- first and returns the existing case, so the index is the second line rather
-- than the only one.
--
-- ADDITIVE, PER THE HARD CONSTRAINT
-- ---------------------------------
-- One nullable column and one index. No column dropped, no row deleted, no
-- existing value rewritten. Every case that exists today keeps
-- `legacy_client_id = null` and stays readable and listable exactly as before;
-- `null` is excluded from the unique index, so any number of them may coexist.
-- The column is nullable on purpose and must stay nullable: a case opened
-- directly in the canonical product has no legacy client to point at.
--
-- `employment_case` already has row level security enabled with a
-- `tenant_id = current_setting('app.tenant_id', true)::uuid` policy (0003:99,
-- :107) and all access goes through `withTenant` in packages/db/src/pool.ts, so
-- this column inherits both. No new table and no new function, so there is
-- nothing here to `revoke ... from public`.

alter table employment_case
  add column if not exists legacy_client_id text;

comment on column employment_case.legacy_client_id is
  'Opaque identifier of the legacy browser client (caredesk.mvp.clients.v1) this case was opened from. Written once at creation, never updated. Null for cases opened directly in the canonical product. ADR-006 provenance marker, not domain data.';

-- One canonical case per legacy client, per tenant. Partial so that the many
-- cases with no legacy client (null) are unconstrained.
create unique index if not exists employment_case_legacy_client_unique
  on employment_case (tenant_id, legacy_client_id)
  where legacy_client_id is not null;

insert into schema_migrations (version) values ('0042_employment_case_legacy_client_link');
